version: '3.1'

services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
      - ./database/zmwm_proc.sql:/root/zmwm_proc.sql
      - ./database/zmwm_table.sql:/root/zmwm_table.sql
    # networks:
    #   - default
    ports:
      - 3306:3306

  wulin:
    build: wulin
    depends_on:
      - database
    # restart: always
    # networks:
    #   - default
    ports:
      - 29000:29000
      # - 36909:36909
      # - 29002:29002
      # - 29100:29100
      # - 29200:29200
      # - 29201:29201
      # - 29211:29211
      # - 29300:29300
      # - 29301:29301
      # - 29302:29302
      # - 29303:29303
      # - 29304:29304
      # - 29305:29305
      # - 29306:29306
      # - 29307:29307
      # - 29308:29308
      # - 29400:29400
      # - 29401:29401
      # - 29500:29500
      # - 29702:29702
      # - 29712:29712
      # - 46602:46602
      # - 41791:41791
      # - 35538:35538
      # - "11100:11100/udp"
      # - "11101:11101"
      # - "37306:37306/udp"
    links:
      - database
    extra_hosts:
      - "PW-Server:127.0.0.1"
      - "aumanager:127.0.0.1"
      - "manager:127.0.0.1"
      - "link1:127.0.0.1"
      - "game1:127.0.0.1"
      - "game2:127.0.0.1"
      - "delivery:127.0.0.1"
      - "backup:127.0.0.1"
      - "auth:127.0.0.1"
      - "audb:127.0.0.1"
      - "gmserver:127.0.0.1"
      - "wulin:127.0.0.1"

    volumes:
      # - ./server/hosts:/etc/hosts
      - ./server/authd.conf:/etc/authd.conf
      - ./server/libtask.so:/lib/libtask.so
      - ./server/libskill.so:/lib/libskill.so
      - ./server/server:/root
    command: ["/root/my"]

# networks:
#   default:
