version: "0.1"

services:
  mongo:
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - .data:/data

  leanote:
    build: leanote
    ports:
      - 9000:9000
    links:
      - mongo
    command: "/bin/bash"

